import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { loginUser } from "../services/authService";

export default function Login(){
 const navigate=useNavigate(); const [form,setForm]=useState({email:"",password:""}); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [show,setShow]=useState(false);
 const submit=async(e)=>{e.preventDefault();setError("");setLoading(true);try{const d=await loginUser(form);localStorage.setItem("token",d.token||d.accessToken||"");localStorage.setItem("role",d.role||"");localStorage.setItem("userId",d.userId||d.id||"");localStorage.setItem("name",d.name||d.firstName||"User");localStorage.setItem("email",d.email||form.email);navigate("/");}catch(err){setError(err.message)}finally{setLoading(false)}};
 return <div className="auth-shell"><section className="auth-visual"><div className="brand-mark">RU</div><div><span className="eyebrow">RESOURCE UTILIZATION PLATFORM</span><h1>Smarter labs.<br/>Better research.</h1><p>Manage equipment, bookings, maintenance and calibration from one secure workspace.</p><div className="feature-row"><span>✓ Live availability</span><span>✓ Centralized bookings</span><span>✓ Asset insights</span></div></div><small>Built for modern institutions and research teams.</small></section><section className="auth-panel"><form className="pro-auth-card" onSubmit={submit}><div className="mobile-brand"><span className="brand-mark small">RU</span> ResourceHub</div><span className="eyebrow dark">WELCOME BACK</span><h2>Sign in to your workspace</h2><p className="subtext">Enter your credentials to continue to ResourceHub.</p>{error&&<div className="pro-alert">⚠ {error}</div>}<label>Email address</label><input type="email" name="email" placeholder="name@institution.edu" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><label>Password</label><div className="password-wrap"><input type={show?"text":"password"} name="password" placeholder="Enter your password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><button type="button" className="show-pass" onClick={()=>setShow(!show)}>{show?"Hide":"Show"}</button></div><div className="auth-options"><label className="check"><input type="checkbox"/> Remember me</label><span>Secure login</span></div><button className="primary-action" disabled={loading}>{loading?"Signing in…":"Sign in →"}</button><p className="auth-switch">New to ResourceHub? <Link to="/register">Create an account</Link></p></form></section></div>
}
