package com.labresource.backend.report.service;

import com.labresource.backend.common.exception.ApiException;
import com.labresource.backend.report.entity.Report;
import com.labresource.backend.report.repository.ReportRepository;
import com.labresource.backend.storage.CloudinaryUploadResult;
import com.labresource.backend.storage.StorageService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;

@Service
@RequiredArgsConstructor
public class ReportService {

    private final ReportRepository reportRepository;
    private final StorageService storageService;

    @Transactional
    public Report generateReport(Long userId, Long institutionId, Long departmentId, String reportType, String format) throws IOException {
        String mockContent = "=== LAB RESOURCE UTILIZATION PLATFORM REPORT ===\n" +
                "Report Type: " + reportType.toUpperCase() + "\n" +
                "Format: " + format.toUpperCase() + "\n" +
                "Generated By User ID: " + userId + "\n" +
                "Institution ID: " + institutionId + "\n" +
                "Department ID: " + (departmentId != null ? departmentId : "All") + "\n" +
                "Generated At: " + java.time.LocalDateTime.now() + "\n" +
                "================================================\n" +
                "Data Summary: Mock data grid representing " + reportType.toLowerCase() + " analytics.";

        byte[] contentBytes = mockContent.getBytes(StandardCharsets.UTF_8);
        String extension = "pdf".equalsIgnoreCase(format) ? ".pdf" : ".xlsx";
        String fileName = reportType.toLowerCase() + "_report_" + System.currentTimeMillis() + extension;
        String contentType = "pdf".equalsIgnoreCase(format) ? "application/pdf" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

        MultipartFile customFile = new SimpleMultipartFile(contentBytes, fileName, contentType);
        CloudinaryUploadResult uploadResult = storageService.upload(customFile, "reports");

        Report report = new Report();
        report.setGeneratedBy(userId);
        report.setReportType(reportType.toUpperCase());
        report.setInstitutionId(institutionId);
        report.setDepartmentId(departmentId);
        report.setCloudinaryPublicId(uploadResult.getPublicId());
        report.setCloudinarySecureUrl(uploadResult.getSecureUrl());
        report.setFileName(fileName);
        report.setContentType(contentType);
        report.setFormat(format.toUpperCase());

        return reportRepository.save(report);
    }

    public List<Report> getReports(Long institutionId, Long departmentId) {
        if (departmentId != null) {
            return reportRepository.findByDepartmentIdOrderByGeneratedAtDesc(departmentId);
        }
        return reportRepository.findByInstitutionIdOrderByGeneratedAtDesc(institutionId);
    }

    private static class SimpleMultipartFile implements MultipartFile {
        private final byte[] content;
        private final String name;
        private final String contentType;

        public SimpleMultipartFile(byte[] content, String name, String contentType) {
            this.content = content;
            this.name = name;
            this.contentType = contentType;
        }

        @Override public String getName() { return name; }
        @Override public String getOriginalFilename() { return name; }
        @Override public String getContentType() { return contentType; }
        @Override public boolean isEmpty() { return content == null || content.length == 0; }
        @Override public long getSize() { return content.length; }
        @Override public byte[] getBytes() throws IOException { return content; }
        @Override public InputStream getInputStream() throws IOException { return new ByteArrayInputStream(content); }
        @Override public void transferTo(File dest) throws IOException, IllegalStateException {
            try (FileOutputStream fos = new FileOutputStream(dest)) {
                fos.write(content);
            }
        }
    }
}
