package com.labresource.backend.report.service;

import com.labresource.backend.report.dto.CostAnalysisReportDto;
import com.labresource.backend.report.dto.ReportMetadataDto;
import com.labresource.backend.report.dto.UtilizationEffectivenessReportDto;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class ReportCsvExportService {

    public byte[] exportUtilizationCsv(UtilizationEffectivenessReportDto report) {
        StringBuilder sb = new StringBuilder();

        // 1. REPORT METADATA
        sb.append("=== REPORT METADATA ===\n");
        ReportMetadataDto meta = report.getMetadata();
        if (meta != null) {
            sb.append("Report Type,").append(escapeCsv(meta.getReportType())).append("\n");
            sb.append("Institution,").append(escapeCsv(meta.getInstitutionName())).append("\n");
            if (meta.getDepartmentName() != null) sb.append("Department,").append(escapeCsv(meta.getDepartmentName())).append("\n");
            if (meta.getLaboratoryName() != null) sb.append("Laboratory,").append(escapeCsv(meta.getLaboratoryName())).append("\n");
            sb.append("From Date,").append(meta.getFrom() != null ? meta.getFrom().toString() : "").append("\n");
            sb.append("To Date,").append(meta.getTo() != null ? meta.getTo().toString() : "").append("\n");
            sb.append("Generated At,").append(meta.getGeneratedAt() != null ? meta.getGeneratedAt().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")) : "").append("\n");
            sb.append("Generated By Role,").append(escapeCsv(meta.getGeneratedByRole())).append("\n");
        }
        sb.append("\n");

        // 2. EXECUTIVE SUMMARY
        sb.append("=== EXECUTIVE UTILIZATION SUMMARY ===\n");
        UtilizationEffectivenessReportDto.UtilizationSummaryDto summary = report.getSummary();
        if (summary != null) {
            sb.append("Average Utilization Percentage,").append(String.format("%.1f%%", summary.getAverageUtilizationPercentage() != null ? summary.getAverageUtilizationPercentage() : 0.0)).append("\n");
            sb.append("Total Used Hours,").append(String.format("%.1f", summary.getTotalUsedHours() != null ? summary.getTotalUsedHours() : 0.0)).append("\n");
            sb.append("Total Available Hours,").append(String.format("%.1f", summary.getTotalAvailableHours() != null ? summary.getTotalAvailableHours() : 0.0)).append("\n");
            sb.append("Total Idle Hours,").append(String.format("%.1f", summary.getTotalIdleHours() != null ? summary.getTotalIdleHours() : 0.0)).append("\n");
            sb.append("Total Equipment Count,").append(summary.getTotalEquipmentCount() != null ? summary.getTotalEquipmentCount() : 0).append("\n");
            sb.append("Total Laboratory Count,").append(summary.getTotalLaboratoryCount() != null ? summary.getTotalLaboratoryCount() : 0).append("\n");
            sb.append("Total Booking Count,").append(summary.getTotalBookingCount() != null ? summary.getTotalBookingCount() : 0).append("\n");
        }
        sb.append("\n");

        // 3. EQUIPMENT UTILIZATION
        sb.append("=== EQUIPMENT UTILIZATION ===\n");
        sb.append("Equipment ID,Equipment Name,Laboratory,Department,Used Hours,Available Hours,Idle Hours,Utilization %,Booking Count,Status\n");
        List<UtilizationEffectivenessReportDto.EquipmentUtilizationItemDto> eqList = report.getEquipmentUtilization();
        if (eqList != null) {
            for (UtilizationEffectivenessReportDto.EquipmentUtilizationItemDto item : eqList) {
                sb.append(item.getEquipmentId()).append(",")
                  .append(escapeCsv(item.getEquipmentName())).append(",")
                  .append(escapeCsv(item.getLaboratoryName())).append(",")
                  .append(escapeCsv(item.getDepartmentName())).append(",")
                  .append(String.format("%.1f", item.getUsedHours())).append(",")
                  .append(String.format("%.1f", item.getAvailableHours())).append(",")
                  .append(String.format("%.1f", item.getIdleHours())).append(",")
                  .append(String.format("%.1f%%", item.getUtilizationPercentage())).append(",")
                  .append(item.getBookingCount() != null ? item.getBookingCount() : 0).append(",")
                  .append(escapeCsv(item.getUtilizationStatus())).append("\n");
            }
        }
        sb.append("\n");

        // 4. UTILIZATION TREND
        sb.append("=== UTILIZATION TREND ===\n");
        sb.append("Period,Used Hours,Available Hours,Idle Hours,Utilization %\n");
        if (report.getUtilizationTrend() != null) {
            for (UtilizationEffectivenessReportDto.UtilizationTrendPointDto pt : report.getUtilizationTrend()) {
                sb.append(escapeCsv(pt.getPeriod())).append(",")
                  .append(String.format("%.1f", pt.getUsedHours())).append(",")
                  .append(String.format("%.1f", pt.getAvailableHours())).append(",")
                  .append(String.format("%.1f", pt.getIdleHours())).append(",")
                  .append(String.format("%.1f%%", pt.getUtilizationPercentage())).append("\n");
            }
        }
        sb.append("\n");

        // 5. DEPARTMENT COMPARISON (IF PRESENT)
        if (report.getDepartmentComparison() != null && !report.getDepartmentComparison().isEmpty()) {
            sb.append("=== DEPARTMENT COMPARISON ===\n");
            sb.append("Department ID,Department Name,Equipment Count,Laboratory Count,Used Hours,Available Hours,Utilization %\n");
            for (UtilizationEffectivenessReportDto.DepartmentUtilizationComparisonDto dept : report.getDepartmentComparison()) {
                sb.append(dept.getDepartmentId()).append(",")
                  .append(escapeCsv(dept.getDepartmentName())).append(",")
                  .append(dept.getEquipmentCount()).append(",")
                  .append(dept.getLaboratoryCount()).append(",")
                  .append(String.format("%.1f", dept.getUsedHours())).append(",")
                  .append(String.format("%.1f", dept.getAvailableHours())).append(",")
                  .append(String.format("%.1f%%", dept.getUtilizationPercentage())).append("\n");
            }
        }

        return sb.toString().getBytes(StandardCharsets.UTF_8);
    }

    public byte[] exportCostCsv(CostAnalysisReportDto report) {
        StringBuilder sb = new StringBuilder();

        // 1. REPORT METADATA
        sb.append("=== REPORT METADATA ===\n");
        ReportMetadataDto meta = report.getMetadata();
        if (meta != null) {
            sb.append("Report Type,").append(escapeCsv(meta.getReportType())).append("\n");
            sb.append("Institution,").append(escapeCsv(meta.getInstitutionName())).append("\n");
            if (meta.getDepartmentName() != null) sb.append("Department,").append(escapeCsv(meta.getDepartmentName())).append("\n");
            sb.append("From Date,").append(meta.getFrom() != null ? meta.getFrom().toString() : "").append("\n");
            sb.append("To Date,").append(meta.getTo() != null ? meta.getTo().toString() : "").append("\n");
            sb.append("Generated At,").append(meta.getGeneratedAt() != null ? meta.getGeneratedAt().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")) : "").append("\n");
            sb.append("Generated By Role,").append(escapeCsv(meta.getGeneratedByRole())).append("\n");
        }
        sb.append("\n");

        // 2. FINANCIAL SUMMARY
        sb.append("=== FINANCIAL COST SUMMARY ===\n");
        CostAnalysisReportDto.CostSummaryBreakdownDto summary = report.getSummary();
        if (summary != null) {
            sb.append("Total Cost Amount,").append(formatMoney(summary.getTotalCost())).append("\n");
            sb.append("Usage Cost,").append(formatMoney(summary.getUsageCost())).append("\n");
            sb.append("Maintenance Expense,").append(formatMoney(summary.getMaintenanceCost())).append("\n");
            sb.append("Sharing Fee,").append(formatMoney(summary.getSharingFee())).append("\n");
            sb.append("Damage Charge,").append(formatMoney(summary.getDamageCharge())).append("\n");
            sb.append("Total Cost Records,").append(summary.getTotalCostsCount() != null ? summary.getTotalCostsCount() : 0).append("\n");
        }
        sb.append("\n");

        // 3. BUDGET AUDIT
        sb.append("=== BUDGET AUDIT ===\n");
        CostAnalysisReportDto.BudgetReportSummaryDto budget = report.getBudget();
        if (budget != null) {
            sb.append("Fiscal Year,").append(escapeCsv(budget.getFiscalYear())).append("\n");
            sb.append("Allocated Budget,").append(formatMoney(budget.getAllocatedAmount())).append("\n");
            sb.append("Used Amount,").append(formatMoney(budget.getUsedAmount())).append("\n");
            sb.append("Remaining Balance,").append(formatMoney(budget.getRemainingAmount())).append("\n");
            sb.append("Consumption Rate,").append(String.format("%.1f%%", budget.getUsedPercentage() != null ? budget.getUsedPercentage().doubleValue() : 0.0)).append("\n");
            sb.append("Warning Status,").append(escapeCsv(budget.getWarningStatus())).append("\n");
        }
        sb.append("\n");

        // 4. EQUIPMENT COSTS
        sb.append("=== EQUIPMENT COSTS ===\n");
        sb.append("Equipment ID,Equipment Name,Laboratory,Department,Usage Cost,Maintenance Cost,Damage Charge,Total Cost\n");
        if (report.getEquipmentCosts() != null) {
            for (CostAnalysisReportDto.EquipmentCostItemDto item : report.getEquipmentCosts()) {
                sb.append(item.getEquipmentId()).append(",")
                  .append(escapeCsv(item.getEquipmentName())).append(",")
                  .append(escapeCsv(item.getLaboratoryName())).append(",")
                  .append(escapeCsv(item.getDepartmentName())).append(",")
                  .append(formatMoney(item.getUsageCost())).append(",")
                  .append(formatMoney(item.getMaintenanceCost())).append(",")
                  .append(formatMoney(item.getDamageCharge())).append(",")
                  .append(formatMoney(item.getTotalCost())).append("\n");
            }
        }
        sb.append("\n");

        // 5. MAINTENANCE COSTS
        sb.append("=== MAINTENANCE EXPENSES ===\n");
        sb.append("Work Order ID,Equipment Name,Laboratory,Created Date,Cost Amount,Status\n");
        if (report.getMaintenanceCosts() != null) {
            for (CostAnalysisReportDto.MaintenanceCostItemDto m : report.getMaintenanceCosts()) {
                sb.append("WO-#").append(m.getMaintenanceId()).append(",")
                  .append(escapeCsv(m.getEquipmentName())).append(",")
                  .append(escapeCsv(m.getLaboratoryName())).append(",")
                  .append(m.getCreatedDate() != null ? m.getCreatedDate().toString() : "").append(",")
                  .append(formatMoney(m.getMaintenanceCost())).append(",")
                  .append(escapeCsv(m.getStatus())).append("\n");
            }
        }
        sb.append("\n");

        // 6. DEPARTMENT COMPARISON (IF PRESENT)
        if (report.getDepartmentComparison() != null && !report.getDepartmentComparison().isEmpty()) {
            sb.append("=== DEPARTMENT COST COMPARISON ===\n");
            sb.append("Department ID,Department Name,Total Cost,Usage Cost,Maintenance Cost,Allocated Budget,Budget Used,Budget Util %\n");
            for (CostAnalysisReportDto.DepartmentCostComparisonDto dept : report.getDepartmentComparison()) {
                sb.append(dept.getDepartmentId()).append(",")
                  .append(escapeCsv(dept.getDepartmentName())).append(",")
                  .append(formatMoney(dept.getTotalCost())).append(",")
                  .append(formatMoney(dept.getUsageCost())).append(",")
                  .append(formatMoney(dept.getMaintenanceCost())).append(",")
                  .append(formatMoney(dept.getBudgetAllocated())).append(",")
                  .append(formatMoney(dept.getBudgetUsed())).append(",")
                  .append(String.format("%.1f%%", dept.getBudgetUtilizationPercentage() != null ? dept.getBudgetUtilizationPercentage().doubleValue() : 0.0)).append("\n");
            }
        }

        return sb.toString().getBytes(StandardCharsets.UTF_8);
    }

    private String escapeCsv(String input) {
        if (input == null) return "";
        if (input.contains(",") || input.contains("\"") || input.contains("\n")) {
            return "\"" + input.replace("\"", "\"\"") + "\"";
        }
        return input;
    }

    private String formatMoney(BigDecimal amount) {
        if (amount == null) return "0";
        return amount.setScale(0, java.math.RoundingMode.HALF_UP).toString();
    }
}
