server:
  port: 8080

spring:
  application:
    name: lab-resource-utilization-platform
  datasource:
    url: jdbc:postgresql://localhost:5433/labdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Senthilp@9943    # <-- Replace with your actual PostgreSQL password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 9a6e8b4e78b2a1649c0d12e5894f3a78c1b9d4e56f7a8b9c0d1e2f3a4b5c6d7e
    expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html