package com.labresource.entity;

public enum NotificationType {

    BOOKING_CONFIRMATION,
    BOOKING_REMINDER,
    BOOKING_APPROVED,
    BOOKING_REJECTED,

    MAINTENANCE_ALERT,
    MAINTENANCE_REQUEST,
    WORK_ORDER_ASSIGNED,
    WORK_ORDER_COMPLETED,

    CALIBRATION_DUE,
    CALIBRATION_EXPIRED,
    CERTIFICATION_EXPIRING,

    WAITLIST_AVAILABLE,

    IDLE_EQUIPMENT,

    SHARING_REQUEST,
    SHARING_APPROVED,
    SHARING_REJECTED,

    BILLING_GENERATED,
    PAYMENT_PENDING,

    SYSTEM_ALERT
}