ALTER TABLE Equipment
    ADD COLUMN hourly_rate DECIMAL(10,2) NULL,
    ADD COLUMN external_hourly_rate DECIMAL(10,2) NULL;

ALTER TABLE Equipment
    ADD CONSTRAINT chk_equipment_hourly_rate CHECK (hourly_rate IS NULL OR hourly_rate >= 0),
    ADD CONSTRAINT chk_equipment_external_rate CHECK (external_hourly_rate IS NULL OR external_hourly_rate >= 0);

ALTER TABLE Booking
    ADD COLUMN estimated_cost DECIMAL(12,2) NULL,
    ADD COLUMN actual_cost DECIMAL(12,2) NULL,
    ADD COLUMN payment_status VARCHAR(20) NOT NULL DEFAULT 'NOT_APPLICABLE';

ALTER TABLE Booking
    ADD CONSTRAINT chk_booking_estimated_cost CHECK (estimated_cost IS NULL OR estimated_cost >= 0),
    ADD CONSTRAINT chk_booking_actual_cost CHECK (actual_cost IS NULL OR actual_cost >= 0),
    ADD CONSTRAINT chk_booking_payment_status CHECK (payment_status IN ('NOT_APPLICABLE','PENDING','PAID','WAIVED'));

ALTER TABLE SharedBooking
    ADD COLUMN estimated_fee DECIMAL(12,2) NULL,
    ADD COLUMN payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';

ALTER TABLE SharedBooking
    ADD CONSTRAINT chk_shared_booking_estimated_fee CHECK (estimated_fee IS NULL OR estimated_fee >= 0),
    ADD CONSTRAINT chk_shared_booking_payment_status CHECK (payment_status IN ('PENDING','INVOICED','PAID','OVERDUE','WAIVED'));

ALTER TABLE CostRecord
    ADD COLUMN sharing_agreement_id BIGINT NULL;

ALTER TABLE CostRecord
    ADD CONSTRAINT fk_cost_sharing_agreement FOREIGN KEY (sharing_agreement_id) REFERENCES SharingAgreement(agreement_id);

ALTER TABLE Invoice
    ADD COLUMN sharing_agreement_id BIGINT NULL,
    ADD COLUMN external_institution_id BIGINT NULL;

ALTER TABLE Invoice
    ADD CONSTRAINT fk_invoice_sharing_agreement FOREIGN KEY (sharing_agreement_id) REFERENCES SharingAgreement(agreement_id),
    ADD CONSTRAINT fk_invoice_external_institution FOREIGN KEY (external_institution_id) REFERENCES Institution(institution_id);

ALTER TABLE MaintenanceRequest
    ADD COLUMN issue_report_id BIGINT NULL,
    ADD COLUMN department_id BIGINT NULL;

ALTER TABLE MaintenanceRequest
    ADD CONSTRAINT fk_maintenance_issue_report FOREIGN KEY (issue_report_id) REFERENCES EquipmentIssueReport(issue_report_id);

ALTER TABLE MaintenanceRequest
    ADD CONSTRAINT fk_maintenance_department FOREIGN KEY (department_id) REFERENCES Department(department_id);

CREATE INDEX idx_maintenance_department_status ON MaintenanceRequest(department_id, status);

UPDATE MaintenanceRequest mr
SET department_id = eq.department_id
FROM Equipment eq
WHERE eq.equipment_id = mr.equipment_id
  AND mr.department_id IS NULL;

ALTER TABLE EquipmentIssueReport
    ADD COLUMN maintenance_id BIGINT NULL;

ALTER TABLE EquipmentIssueReport
    ADD CONSTRAINT fk_issue_report_maintenance FOREIGN KEY (maintenance_id) REFERENCES MaintenanceRequest(maintenance_id);

CREATE TABLE EquipmentCertification (
    certification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL,
    certificate_name VARCHAR(150) NOT NULL,
    certificate_number VARCHAR(100),
    issued_by VARCHAR(150),
    issue_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    certificate_public_id VARCHAR(500),
    certificate_secure_url VARCHAR(1000),
    certificate_file_name VARCHAR(255),
    certificate_content_type VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'VALID',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_certification_equipment FOREIGN KEY (equipment_id) REFERENCES Equipment(equipment_id),
    CONSTRAINT chk_certification_status CHECK (status IN ('VALID','EXPIRING_SOON','EXPIRED','REVOKED')),
    CONSTRAINT chk_certification_dates CHECK (expiry_date >= issue_date)
);

CREATE TRIGGER trg_equipmentcertification_set_updated_at
    BEFORE UPDATE ON EquipmentCertification
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_certification_equipment_status ON EquipmentCertification(equipment_id, status);
CREATE INDEX idx_certification_expiry ON EquipmentCertification(expiry_date);
