-- Migration V5: Laboratory Hierarchy, MaintenanceRecord, Budget Single Source of Truth, Budget Requests, Damage Liability & Institution Bank Accounts

-- Phase 1: Laboratory Table & Equipment/Department Image Links
CREATE TABLE IF NOT EXISTS Laboratory (
    lab_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    location VARCHAR(150),
    capacity INT DEFAULT 1,
    image_public_id VARCHAR(500),
    image_secure_url VARCHAR(1000),
    image_file_name VARCHAR(255),
    image_content_type VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lab_institution FOREIGN KEY (institution_id) REFERENCES Institution(institution_id),
    CONSTRAINT fk_lab_department FOREIGN KEY (department_id) REFERENCES Department(department_id)
);

ALTER TABLE Equipment ADD COLUMN IF NOT EXISTS lab_id BIGINT NULL;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_equipment_lab') THEN
        ALTER TABLE Equipment ADD CONSTRAINT fk_equipment_lab FOREIGN KEY (lab_id) REFERENCES Laboratory(lab_id);
    END IF;
END $$;

ALTER TABLE Department
    ADD COLUMN IF NOT EXISTS image_public_id VARCHAR(500),
    ADD COLUMN IF NOT EXISTS image_secure_url VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS image_file_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS image_content_type VARCHAR(100);

-- Phase 2: MaintenanceRecord Entity & Table
CREATE TABLE IF NOT EXISTS MaintenanceRecord (
    maintenance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL,
    technician_id BIGINT NULL,
    issue_report_id BIGINT NULL,
    maintenance_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    reason TEXT,
    description TEXT,
    inspection_notes TEXT,
    work_performed TEXT,
    parts_used TEXT,
    parts_cost DECIMAL(12,2) DEFAULT 0.00,
    labour_cost DECIMAL(12,2) DEFAULT 0.00,
    total_cost DECIMAL(12,2) DEFAULT 0.00,
    condition_before VARCHAR(100),
    condition_after VARCHAR(100),
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    next_maintenance_date DATE NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_maint_rec_equipment FOREIGN KEY (equipment_id) REFERENCES Equipment(equipment_id),
    CONSTRAINT fk_maint_rec_technician FOREIGN KEY (technician_id) REFERENCES AppUser(user_id),
    CONSTRAINT fk_maint_rec_issue FOREIGN KEY (issue_report_id) REFERENCES EquipmentIssueReport(issue_report_id)
);

-- Phase 3: CostRecord Maintenance Link & Idempotency
ALTER TABLE CostRecord ADD COLUMN IF NOT EXISTS maintenance_id BIGINT NULL;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cost_maintenance_rec') THEN
        ALTER TABLE CostRecord ADD CONSTRAINT fk_cost_maintenance_rec FOREIGN KEY (maintenance_id) REFERENCES MaintenanceRecord(maintenance_id);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_maint_cost ON CostRecord(maintenance_id) WHERE cost_type = 'MAINTENANCE';

-- Phase 4: Budget Uniqueness & Single Source of Truth
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_budget_dept_fiscal') THEN
        ALTER TABLE Budget ADD CONSTRAINT uq_budget_dept_fiscal UNIQUE (department_id, fiscal_year);
    END IF;
END $$;

-- Phase 5: BudgetRequest
CREATE TABLE IF NOT EXISTS BudgetRequest (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    institution_id BIGINT NOT NULL,
    fiscal_year VARCHAR(20) NOT NULL,
    requested_amount DECIMAL(14,2) NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    requested_by BIGINT NOT NULL,
    reviewed_by BIGINT NULL,
    reviewed_at TIMESTAMP NULL,
    review_comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_budget_req_dept FOREIGN KEY (department_id) REFERENCES Department(department_id),
    CONSTRAINT fk_budget_req_inst FOREIGN KEY (institution_id) REFERENCES Institution(institution_id),
    CONSTRAINT fk_budget_req_requester FOREIGN KEY (requested_by) REFERENCES AppUser(user_id),
    CONSTRAINT fk_budget_req_reviewer FOREIGN KEY (reviewed_by) REFERENCES AppUser(user_id)
);

-- Phase 6: Damage Inspection & Liability Fields on EquipmentIssueReport
ALTER TABLE EquipmentIssueReport
    ADD COLUMN IF NOT EXISTS condition_before VARCHAR(100),
    ADD COLUMN IF NOT EXISTS observed_problem TEXT,
    ADD COLUMN IF NOT EXISTS inspection_notes TEXT,
    ADD COLUMN IF NOT EXISTS estimated_repair_cost DECIMAL(12,2) DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS recommended_action VARCHAR(100),
    ADD COLUMN IF NOT EXISTS liability_type VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS student_liability_amount DECIMAL(12,2) DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS liability_decided_by BIGINT NULL,
    ADD COLUMN IF NOT EXISTS liability_decided_at TIMESTAMP NULL;

-- Phase 7: Bank Account Management & Primary Constraint
CREATE TABLE IF NOT EXISTS InstitutionBankAccount (
    bank_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id BIGINT NOT NULL,
    account_holder_name VARCHAR(150) NOT NULL,
    bank_name VARCHAR(150) NOT NULL,
    account_number VARCHAR(100) NOT NULL,
    ifsc_code VARCHAR(30) NOT NULL,
    account_type VARCHAR(30) DEFAULT 'SAVINGS',
    is_primary BOOLEAN NOT NULL DEFAULT TRUE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bank_institution FOREIGN KEY (institution_id) REFERENCES Institution(institution_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_primary_bank ON InstitutionBankAccount(institution_id) WHERE is_primary = TRUE;
