-- Migration V8: Staff Invitation Schema & Partial Role Uniqueness Constraints

CREATE TABLE IF NOT EXISTS StaffInvitation (
    invitation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    institution_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    role_name VARCHAR(50) NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    invited_by BIGINT,
    accepted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invitation_institution FOREIGN KEY (institution_id) REFERENCES Institution(institution_id),
    CONSTRAINT fk_invitation_department FOREIGN KEY (department_id) REFERENCES Department(department_id),
    CONSTRAINT fk_invitation_invited_by FOREIGN KEY (invited_by) REFERENCES AppUser(user_id)
);

-- Partial Unique Index to enforce single pending/accepted Department Head per department
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_uq_dept_head_invitation') THEN
        CREATE UNIQUE INDEX idx_uq_dept_head_invitation ON StaffInvitation(institution_id, department_id, role_name)
        WHERE role_name = 'DEPARTMENT_HEAD' AND status IN ('PENDING', 'ACCEPTED');
    END IF;
END $$;

-- Partial Unique Index to enforce single pending/accepted Lab Manager per department
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_uq_lab_mgr_invitation') THEN
        CREATE UNIQUE INDEX idx_uq_lab_mgr_invitation ON StaffInvitation(institution_id, department_id, role_name)
        WHERE role_name = 'LAB_MANAGER' AND status IN ('PENDING', 'ACCEPTED');
    END IF;
END $$;
