package com.labresource.backend.session.service;

import com.labresource.backend.session.entity.RefreshToken;
import com.labresource.backend.session.entity.UserSession;
import com.labresource.backend.session.repository.RefreshTokenRepository;
import com.labresource.backend.session.repository.UserSessionRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class SessionService {

    private final RefreshTokenRepository refreshTokenRepository;
    private final UserSessionRepository userSessionRepository;

    @Transactional
    public String createRefreshToken(Long userId) {
        // Revoke old tokens first
        refreshTokenRepository.deleteByUserId(userId);

        RefreshToken refreshToken = new RefreshToken();
        refreshToken.setUserId(userId);
        refreshToken.setToken(UUID.randomUUID().toString());
        refreshToken.setExpiresAt(LocalDateTime.now().plusDays(7)); // 7 days expiration
        refreshToken.setIsRevoked(false);

        return refreshTokenRepository.save(refreshToken).getToken();
    }

    @Transactional
    public void createSession(Long userId, String ipAddress, String userAgent) {
        // Mark previous active sessions as inactive/logged out
        List<UserSession> activeSessions = userSessionRepository.findByUserIdAndSessionStatus(userId, "ACTIVE");
        for (UserSession s : activeSessions) {
            s.setSessionStatus("LOGGED_OUT");
            s.setLogoutAt(LocalDateTime.now());
            userSessionRepository.save(s);
        }

        UserSession session = new UserSession();
        session.setUserId(userId);
        session.setIpAddress(ipAddress);
        session.setUserAgent(userAgent);
        // Note loginAt is generated by DB default, but we can set lastActivityAt
        session.setLastActivityAt(LocalDateTime.now());
        session.setSessionStatus("ACTIVE");
        userSessionRepository.save(session);
    }

    @Transactional
    public void logout(Long userId) {
        refreshTokenRepository.deleteByUserId(userId);

        List<UserSession> activeSessions = userSessionRepository.findByUserIdAndSessionStatus(userId, "ACTIVE");
        for (UserSession s : activeSessions) {
            s.setSessionStatus("LOGGED_OUT");
            s.setLogoutAt(LocalDateTime.now());
            userSessionRepository.save(s);
        }
    }
}
