export const ROLES = {
  RESEARCHER: "RESEARCHER",
  LAB_TECHNICIAN: "LAB_TECHNICIAN",
  LAB_MANAGER: "LAB_MANAGER",
  DEPARTMENT_HEAD: "DEPARTMENT_HEAD",
  INSTITUTION_ADMIN: "INSTITUTION_ADMIN",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
};


// =========================================================
// ROLE GROUPS
// =========================================================

export const ALL_ROLES = [
  ROLES.RESEARCHER,
  ROLES.LAB_TECHNICIAN,
  ROLES.LAB_MANAGER,
  ROLES.DEPARTMENT_HEAD,
  ROLES.INSTITUTION_ADMIN,
  ROLES.SYSTEM_ADMIN,
];


export const MANAGEMENT_ROLES = [
  ROLES.LAB_MANAGER,
  ROLES.DEPARTMENT_HEAD,
  ROLES.INSTITUTION_ADMIN,
  ROLES.SYSTEM_ADMIN,
];


export const ADMIN_ROLES = [
  ROLES.INSTITUTION_ADMIN,
  ROLES.SYSTEM_ADMIN,
];


export const COST_MANAGEMENT_ROLES = [
  ROLES.LAB_MANAGER,
  ROLES.DEPARTMENT_HEAD,
  ROLES.INSTITUTION_ADMIN,
  ROLES.SYSTEM_ADMIN,
];


export const MAINTENANCE_ROLES = [
  ROLES.LAB_TECHNICIAN,
  ROLES.LAB_MANAGER,
  ROLES.DEPARTMENT_HEAD,
  ROLES.INSTITUTION_ADMIN,
  ROLES.SYSTEM_ADMIN,
];


export const CALIBRATION_ROLES = [
  ROLES.LAB_TECHNICIAN,
  ROLES.LAB_MANAGER,
  ROLES.DEPARTMENT_HEAD,
  ROLES.INSTITUTION_ADMIN,
  ROLES.SYSTEM_ADMIN,
];


export const BOOKING_APPROVAL_ROLES = [
  ROLES.LAB_MANAGER,
  ROLES.DEPARTMENT_HEAD,
  ROLES.INSTITUTION_ADMIN,
  ROLES.SYSTEM_ADMIN,
];


export const EXTERNAL_ACCESS_ROLES = [
  ROLES.LAB_MANAGER,
  ROLES.INSTITUTION_ADMIN,
  ROLES.SYSTEM_ADMIN,
];


export const WAITLIST_MANAGEMENT_ROLES = [
  ROLES.LAB_MANAGER,
  ROLES.SYSTEM_ADMIN,
];


export const REPORT_ROLES = [
  ROLES.LAB_MANAGER,
  ROLES.DEPARTMENT_HEAD,
  ROLES.INSTITUTION_ADMIN,
  ROLES.SYSTEM_ADMIN,
];