// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/role-based-lab-dashboard/RoleBasedDashboard.tsx": () => import("../components/mockups/role-based-lab-dashboard/RoleBasedDashboard.tsx")
};
