# Server Configuration
server.port=8080
server.error.include-message=always

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_resource_utilization
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
security.jwt.secret=fhvudgiydfcohjjhbviufcvhhgvikjbvbhjdocgfiydxyijh-9iotgd7fdffbfbfdgfbnbbersvsdfwvsc