spring.application.name=lab-resource-auth-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_resource_db
spring.datasource.username=postgres
spring.datasource.password=AByadav@07
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_MIN_32_CHARS
jwt.expiration-ms=86400000

server.port=8080
