package com.labresource.enums;

public enum NotificationType {
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    EQUIPMENT_AVAILABLE,
    WAITLIST_ALLOCATED,
    WAITLIST_EXPIRED,
    RESOURCE_SHARING_APPROVED,
    RESOURCE_SHARING_REJECTED,
    MAINTENANCE,
    CALIBRATION,
    GENERAL
}
